name: jmix-observability-tracing

services:

  postgres:
    build:
      context: ./postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  petclinic:
    profiles: [app]
    build:
      context: ../jmix-petclinic-2
    depends_on:
      postgres:
        condition: service_healthy
      lgtm:
        condition: service_started
    environment:
      MAIN_DATASOURCE_URL: jdbc:postgresql://postgres:5432/petclinic
      MAIN_DATASOURCE_USERNAME: postgres
      MAIN_DATASOURCE_PASSWORD: postgres
      # tag::otel-environment[]
      MANAGEMENT_OPENTELEMETRY_LOGGING_EXPORT_OTLP_ENDPOINT: http://lgtm:4318/v1/logs
      MANAGEMENT_OPENTELEMETRY_TRACING_EXPORT_OTLP_ENDPOINT: http://lgtm:4318/v1/traces
      MANAGEMENT_OTLP_METRICS_EXPORT_URL: http://lgtm:4318/v1/metrics
      # end::otel-environment[]
    ports:
      - "8080:8080"

  petclinic-portal:
    profiles: [app]
    build:
      context: ../jmix-petclinic-portal
    depends_on:
      postgres:
        condition: service_healthy
      lgtm:
        condition: service_started
      petclinic:
        condition: service_started
    environment:
      MAIN_DATASOURCE_URL: jdbc:postgresql://postgres:5432/portal
      MAIN_DATASOURCE_USERNAME: postgres
      MAIN_DATASOURCE_PASSWORD: postgres
      PETCLINIC_BASEURL: http://petclinic:8080
      PETCLINIC_CLIENTID: petclinic-portal
      PETCLINIC_CLIENTSECRET: UYfIcnMhoL
      MANAGEMENT_OPENTELEMETRY_LOGGING_EXPORT_OTLP_ENDPOINT: http://lgtm:4318/v1/logs
      MANAGEMENT_OPENTELEMETRY_TRACING_EXPORT_OTLP_ENDPOINT: http://lgtm:4318/v1/traces
      MANAGEMENT_OTLP_METRICS_EXPORT_URL: http://lgtm:4318/v1/metrics
    ports:
      - "8081:8081"

  # tag::lgtm[]
  lgtm:
    image: grafana/otel-lgtm:0.29.1
    ports:
      - "3000:3000" # Grafana
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
  # end::lgtm[]

networks:
  default:
    name: jmix-observability-tracing
