# tag::start[]
apiVersion: 1

datasources:
# end::start[]

# tag::loki-with-traces[]
  - name: Loki
    type: loki
    uid: loki
    url: http://loki:3100
    jsonData:
      derivedFields:
        - name: 'trace_id'
          matcherRegex: '"traceid":"(\w+)"'
          url: '$${__value.raw}'
          datasourceUid: 'tempo'
# end::loki-with-traces[]

# tag::tempo-with-logs[]
  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3200
    jsonData:
      tracesToLogs:
        datasourceUid: 'loki'
        mappedTags: [{key: 'service.name', value: 'job'}]
        mapTagNamesEnabled: true
        filterByTraceID: true
      search:
        hide: false
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: 'loki'
# end::tempo-with-logs[]
