# tag::receivers-with-traces[]
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
# end::receivers-with-traces[]

# tag::processors[]
processors:
  batch:
# end::processors[]

# tag::exporters-with-traces[]
exporters:
  debug:
    verbosity: detailed
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
  otlphttp:
    endpoint: "http://tempo:4418"
# end::exporters-with-traces[]

# tag::service-with-traces[]
service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp, debug]
# end::service-with-traces[]
